# ./buildafa_trie_heap_printsattimes/triesat < ../afacomp/afacomp_simpl_tseytin/bool_comb/78.antisat > sattimes_trie1.log
# ./buildafa_clause_heap_printsattimes/triesat < ../afacomp/afacomp_simpl_tseytin/bool_comb/78.antisat > sattimes_clause1.log
# ./buildafa_trie_heap_printsattimes/triesat < ../afacomp/afacomp_simpl_tseytin/noodler/12706.antisat > sattimes_trie2.log
# ./buildafa_clause_heap_printsattimes/triesat < ../afacomp/afacomp_simpl_tseytin/noodler/12706.antisat > sattimes_clause2.log
# ./buildafa_trie_heap_printsattimes/triesat < ../afacomp/afacomp_simpl_tseytin/ltl_afa/5759.antisat > sattimes_trie3.log
# ./buildafa_clause_heap_printsattimes/triesat < ../afacomp/afacomp_simpl_tseytin/ltl_afa/5759.antisat > sattimes_clause3.log
# ./buildafa_trie_heap_printsattimes/triesat < ../afacomp/afacomp_simpl_tseytin/stranger_afa/1551.antisat > sattimes_trie4.log
# ./buildafa_clause_heap_printsattimes/triesat < ../afacomp/afacomp_simpl_tseytin/stranger_afa/1551.antisat > sattimes_clause4.log
# ./buildafa_trie_heap_printsattimes/triesat < ../afacomp/afacomp_simpl_tseytin/automata_inclusion/99.antisat > sattimes_trie5.log
# ./buildafa_clause_heap_printsattimes/triesat < ../afacomp/afacomp_simpl_tseytin/automata_inclusion/99.antisat > sattimes_clause5.log
# ./buildafa_trie_heap_printsattimes/triesat < ../afacomp/afacomp_simpl_tseytin/noodler/12907.antisat > sattimes_trie6.log
# ./buildafa_trie_heap_reverseadd_printsattimes/triesat < ../afacomp/afacomp_simpl_tseytin/noodler/12907.antisat > sattimes_trierev6.log
# ./buildafa_trie_heap_setsuccone_printsattimes/triesat < ../afacomp/afacomp_simpl_tseytin/noodler/12907.antisat > sattimes_triesso6.log
